// Content templates grid — triggers real AI generation via the ai-generate edge fn.

import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import { Sparkles, Loader2, Lightbulb, Camera, Anchor, MessageCircleQuestion, Quote, Check, AlertCircle } from "lucide-react";
import { useAtlas } from "@/lib/context";
import { generateContent } from "@/lib/ai";
import { Modal } from "./Modal";
import type { LucideIcon } from "lucide-react";

interface Template { id: string; labelKey: string; icon: LucideIcon; prompt: string; tone: string }

const TEMPLATES: Template[] = [
  { id: "starter", labelKey: "templates.starter", icon: Sparkles, prompt: "A bold, attention-grabbing starter post introducing a new product or idea.", tone: "confident" },
  { id: "bts", labelKey: "templates.bts", icon: Camera, prompt: "A behind-the-scenes look at how the team builds or creates something.", tone: "authentic" },
  { id: "hook", labelKey: "templates.hook", icon: Anchor, prompt: "A scroll-stopping hook line that makes people stop and read.", tone: "punchy" },
  { id: "question", labelKey: "templates.question", icon: MessageCircleQuestion, prompt: "An engaging question that sparks comments and discussion.", tone: "friendly" },
  { id: "quote", labelKey: "templates.quote", icon: Quote, prompt: "An inspirational quote post with a short reflective caption.", tone: "inspiring" },
  { id: "lightbulb", labelKey: "templates.starter", icon: Lightbulb, prompt: "A quick tip or insight the audience can apply today.", tone: "helpful" },
];

export function ContentTemplates() {
  const { t, channels } = useAtlas();
  const [active, setActive] = useState<Template | null>(null);
  const [loading, setLoading] = useState(false);
  const [variants, setVariants] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<string | null>(null);
  const [note, setNote] = useState<string | null>(null);

  async function generate(tpl: Template) {
    setActive(tpl);
    setVariants([]); setError(null); setNote(null); setSource(null);
    setLoading(true);
    const platform = channels[0]?.service ?? "twitter";
    const { data, error } = await generateContent(tpl.prompt, { tone: tpl.tone, platform });
    setLoading(false);
    if (error) { setError(error); return; }
    if (data) {
      setVariants(data.variants);
      setSource(data.source);
      if (data.note) setNote(data.note);
    }
  }

  return (
    <div className="card p-5">
      <div className="mb-4">
        <h3 className="text-sm font-semibold text-white">{t("templates.title")}</h3>
        <p className="text-xs text-white/50 mt-0.5">{t("templates.subtitle")}</p>
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">
        {TEMPLATES.map((tpl, i) => {
          const Icon = tpl.icon;
          return (
            <motion.button
              key={tpl.id + i}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.04 }}
              whileHover={{ y: -2 }}
              onClick={() => generate(tpl)}
              className="card card-hover p-4 text-left group"
            >
              <Icon size={18} className="text-atlas-300 mb-2.5 group-hover:text-accent transition-colors" />
              <div className="text-xs font-medium text-white/90">{t(tpl.labelKey)}</div>
              <div className="text-[10px] text-white/40 mt-0.5 line-clamp-2">{tpl.prompt}</div>
            </motion.button>
          );
        })}
      </div>

      <Modal open={!!active} onClose={() => setActive(null)} title={active ? t(active.labelKey) : ""} subtitle="AI-generated drafts" maxWidth="max-w-lg">
        {loading ? (
          <div className="flex flex-col items-center py-10">
            <Loader2 size={28} className="animate-spin text-atlas-300 mb-3" />
            <p className="text-sm text-white/50">Generating drafts…</p>
          </div>
        ) : error ? (
          <div className="flex items-start gap-2 rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-2 text-sm text-red-400">
            <AlertCircle size={16} className="mt-0.5 shrink-0" />
            <span>{error}</span>
          </div>
        ) : (
          <div className="space-y-3">
            {note && (
              <div className="rounded-lg border border-amber-500/20 bg-amber-500/10 px-3 py-2 text-xs text-amber-400">{note}</div>
            )}
            <AnimatePresence>
              {variants.map((v, i) => <DraftCard key={i} text={v} />)}
            </AnimatePresence>
            {source === "openai" && (
              <p className="text-[10px] text-white/30 text-center">Generated by OpenAI via Atlas</p>
            )}
          </div>
        )}
      </Modal>
    </div>
  );
}

function DraftCard({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-lg border border-white/[0.08] bg-white/[0.02] p-3"
    >
      <p className="text-sm text-white/85 whitespace-pre-wrap break-words">{text}</p>
      <button
        onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); }}
        className="mt-2 inline-flex items-center gap-1 text-xs text-atlas-300 hover:text-atlas-200"
      >
        {copied ? <><Check size={12} /> Copied</> : "Copy"}
      </button>
    </motion.div>
  );
}
